#!/usr/bin/env node
import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';

const program = new Command();
program.name('ai-prompt-test').description('Unit testing for prompts.').version('1.0.0');

program.command('init').description('Generate prompt test template').option('-d, --dir <path>', 'Output directory', './prompts').action((options) => {
  const dir = options.dir;
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  
  const template = `// Prompt Tests - Generated by ai-prompt-test
import { runPromptTests, PromptTest } from 'ai-prompt-test';

const tests: PromptTest[] = [
  { name: 'greeting', prompt: 'Say hello to {{name}}', variables: { name: 'Alice' }, expect: { contains: ['Alice'] } },
  { name: 'short response', prompt: 'Briefly explain AI', expect: { maxLength: 500 } },
];

async function llm(prompt: string): Promise<string> {
  // Your LLM call
  return '';
}

runPromptTests(tests, llm).then(r => console.log(JSON.stringify(r, null, 2)));`;
  
  fs.writeFileSync(`${dir}/tests.ts`, template);
  console.log(chalk.green(`✓ Created ${dir}/tests.ts`));
  console.log(chalk.cyan('\\n✅ Prompt tests generated!'));
});

program.parse();
